version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - redis
    command: celery -A file_converter worker --loglevel=info

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379